if(NOT DEFINED GENERATOR)
  message(FATAL_ERROR "GENERATOR is required")
endif()
set(work "${CMAKE_CURRENT_BINARY_DIR}/host-operations-registry-test")
file(MAKE_DIRECTORY "${work}")
file(WRITE "${work}/unknown.wsm" "(host-operations/1\n  (cp:0001 (surface uk log) (arity 0) (effect log) (result nil))\n  (cp:ABCD (surface uk broken) (arity 0) (effect inspect) (result nil))\n)\n")
execute_process(COMMAND "${CMAKE_COMMAND}" -DINPUT=${work}/unknown.wsm -DOUTPUT=${work}/unknown.hpp -P "${GENERATOR}" RESULT_VARIABLE rc OUTPUT_VARIABLE stdout ERROR_VARIABLE stderr)
if(rc EQUAL 0)
  message(FATAL_ERROR "unknown cp: ID was accepted; expected fail-closed rejection")
endif()
message(STATUS "host operation registry rejects unknown cp: IDs")