# Generates a C++ projection of adapter/host-operations.wsm.
# Registry data, rather than C++ spelling literals, is the authority for
# local host-operation IDs and public surfaces.
file(READ "${INPUT}" source)
if(NOT source MATCHES "\\(host-operations/2")
  message(FATAL_ERROR "host operation registry must declare host-operations/2: ${INPUT}")
endif()
string(REGEX MATCHALL "\\(cp:[^ \\r\\n)]*" declared_ids "${source}")
foreach(declared_id IN LISTS declared_ids)
  if(NOT declared_id MATCHES "^\\(cp:[0-9][0-9][0-9][0-9]$")
    message(FATAL_ERROR "host operation registry has unknown ID format: ${declared_id}")
  endif()
endforeach()
string(REGEX MATCHALL "\\(cp:[0-9][0-9][0-9][0-9] \\(semantic-id [^)]+\\) \\(surface uk [^)]+\\) \\(arity [0-9]+\\) \\(effect [^)]+\\) \\(input [^)]+\\) \\(result [^)]+\\) \\(owner [^)]+\\) \\(ffi [^)]+\\) \\(status [^)]+\\) \\(evidence [^)]+\\)\\)" entries "${source}")
if(NOT entries)
  message(FATAL_ERROR "host operation registry has no valid entries: ${INPUT}")
endif()
file(WRITE "${OUTPUT}" "// Generated from adapter/host-operations.wsm. DO NOT EDIT.\n#pragma once\n\nnamespace host_operations {\nstruct Operation { const char* id; const char* semanticId; const char* surface; unsigned arity; const char* effect; const char* input; const char* result; const char* owner; const char* ffi; const char* status; const char* evidence; };\n")
if(DEFINED MARKDOWN_OUTPUT)
  file(WRITE "${MARKDOWN_OUTPUT}" "# Generated Cyberpunk host operations\n\n| ID | Surface | Arity | Effect | Input | Result | Owner | FFI | Status | Evidence |\n| --- | --- | ---: | --- | --- | --- | --- | --- | --- | --- |\n")
endif()
set(ids)
set(surfaces)
foreach(entry IN LISTS entries)
  string(REGEX REPLACE ".*\\(cp:([0-9][0-9][0-9][0-9]).*" "\\1" id "${entry}")
  string(REGEX REPLACE ".*\\(surface uk ([^)]+)\\).*" "\\1" surface "${entry}")
  string(REGEX REPLACE ".*\\(arity ([0-9]+)\\).*" "\\1" arity "${entry}")
  string(REGEX REPLACE ".*\\(effect ([^)]+)\\).*" "\\1" effect "${entry}")
  string(REGEX REPLACE ".*\\(semantic-id ([^)]+)\\).*" "\\1" semantic_id "${entry}")
  string(REGEX REPLACE ".*\\(input ([^)]+)\\).*" "\\1" input "${entry}")
  string(REGEX REPLACE ".*\\(result ([^)]+)\\).*" "\\1" result "${entry}")
  string(REGEX REPLACE ".*\\(owner ([^)]+)\\).*" "\\1" owner "${entry}")
  string(REGEX REPLACE ".*\\(ffi ([^)]+)\\).*" "\\1" ffi "${entry}")
  string(REGEX REPLACE ".*\\(status ([^)]+)\\).*" "\\1" status "${entry}")
  string(REGEX REPLACE ".*\\(evidence ([^)]+)\\).*" "\\1" evidence "${entry}")
  if(NOT semantic_id MATCHES "^(none|[0-9][0-9][0-9][0-9])$")
    message(FATAL_ERROR "host operation registry has invalid semantic-id: ${entry}")
  endif()
  if(NOT effect MATCHES "^(inspect|read|invoke-readonly|mutate)$")
    message(FATAL_ERROR "host operation registry has invalid effect: ${entry}")
  endif()
  if(NOT owner MATCHES "^(my-lisp|cyberpunk-host|REDengine)$")
    message(FATAL_ERROR "host operation registry has invalid owner: ${entry}")
  endif()
  # Keep host capability metadata inside the value kinds the checked host
  # boundary can represent without inventing a second untyped value channel.
  # Canonical values keep their exact kind; GameHandle is the explicit
  # Cyberpunk-owned opaque kind. Expanding this vocabulary is an ABI change.
  if(NOT input MATCHES "^(none|truth|fixnum|symbol|string|rational|game-handle)$")
    message(FATAL_ERROR "host operation registry has invalid input kind: ${entry}")
  endif()
  if(NOT result MATCHES "^(nil|truth|fixnum|symbol|string|rational|game-handle)$")
    message(FATAL_ERROR "host operation registry has invalid result kind: ${entry}")
  endif()
  list(FIND ids "${id}" repeated_id)
  list(FIND surfaces "${surface}" repeated_surface)
  if(NOT repeated_id EQUAL -1 OR NOT repeated_surface EQUAL -1)
    message(FATAL_ERROR "host operation registry has duplicate ID or surface: ${entry}")
  endif()
  list(APPEND ids "${id}")
  list(APPEND surfaces "${surface}")
  file(APPEND "${OUTPUT}" "inline constexpr Operation OP_CP_${id}{\"cp:${id}\", \"${semantic_id}\", \"${surface}\", ${arity}, \"${effect}\", \"${input}\", \"${result}\", \"${owner}\", \"${ffi}\", \"${status}\", \"${evidence}\"};\n")
  if(DEFINED MARKDOWN_OUTPUT)
    file(APPEND "${MARKDOWN_OUTPUT}" "| cp:${id} | ${surface} | ${arity} | ${effect} | ${input} | ${result} | ${owner} | ${ffi} | ${status} | ${evidence} |\n")
  endif()
endforeach()
file(APPEND "${OUTPUT}" "} // namespace host_operations\n")
