# Generates a C++ projection of adapter/host-operations.wsm.
# Registry data, rather than C++ spelling literals, is the authority for
# local host-operation IDs and public surfaces.
file(READ "${INPUT}" source)
string(REGEX MATCHALL "\\(cp:[^ \\r\\n)]*" declared_ids "${source}")
foreach(declared_id IN LISTS declared_ids)
  if(NOT declared_id MATCHES "^\\(cp:[0-9][0-9][0-9][0-9]$")
    message(FATAL_ERROR "host operation registry has unknown ID format: ${declared_id}")
  endif()
endforeach()
string(REGEX MATCHALL "\\(cp:[0-9][0-9][0-9][0-9] \\(surface uk [^)]+\\) \\(arity [0-9]+\\) \\(effect [^)]+\\) \\(result [^)]+\\)\\)" entries "${source}")
if(NOT entries)
  message(FATAL_ERROR "host operation registry has no valid entries: ${INPUT}")
endif()
file(WRITE "${OUTPUT}" "// Generated from adapter/host-operations.wsm. DO NOT EDIT.\n#pragma once\n\nnamespace host_operations {\nstruct Operation { const char* id; const char* surface; unsigned arity; const char* effect; const char* result; };\n")
set(ids)
set(surfaces)
foreach(entry IN LISTS entries)
  string(REGEX REPLACE ".*\\(cp:([0-9][0-9][0-9][0-9]).*" "\\1" id "${entry}")
  string(REGEX REPLACE ".*\\(surface uk ([^)]+)\\).*" "\\1" surface "${entry}")
  string(REGEX REPLACE ".*\\(arity ([0-9]+)\\).*" "\\1" arity "${entry}")
  string(REGEX REPLACE ".*\\(effect ([^)]+)\\).*" "\\1" effect "${entry}")
  string(REGEX REPLACE ".*\\(result ([^)]+)\\).*" "\\1" result "${entry}")
  list(FIND ids "${id}" repeated_id)
  list(FIND surfaces "${surface}" repeated_surface)
  if(NOT repeated_id EQUAL -1 OR NOT repeated_surface EQUAL -1)
    message(FATAL_ERROR "host operation registry has duplicate ID or surface: ${entry}")
  endif()
  list(APPEND ids "${id}")
  list(APPEND surfaces "${surface}")
  file(APPEND "${OUTPUT}" "inline constexpr Operation OP_CP_${id}{\"cp:${id}\", \"${surface}\", ${arity}, \"${effect}\", \"${result}\"};\n")
endforeach()
file(APPEND "${OUTPUT}" "} // namespace host_operations\n")