# Generates C++ binding surfaces from adapter/host-bindings.lisp.
file(READ "${INPUT}" source)
string(REGEX MATCHALL "\\(cpb:[^ \\r\\n)]*" declared_ids "${source}")
foreach(declared_id IN LISTS declared_ids)
  if(NOT declared_id MATCHES "^\\(cpb:[0-9][0-9][0-9][0-9]$")
    message(FATAL_ERROR "host binding registry has unknown ID format: ${declared_id}")
  endif()
endforeach()
string(REGEX MATCHALL "\\(cpb:[0-9][0-9][0-9][0-9] \\(surface uk [^)]+\\) \\(kind [^)]+\\) \\(owner [^)]+\\)\\)" entries "${source}")
if(NOT entries)
  message(FATAL_ERROR "host binding registry has no valid entries: ${INPUT}")
endif()
file(WRITE "${OUTPUT}" "// Generated from adapter/host-bindings.lisp. DO NOT EDIT.\n#pragma once\n\nnamespace host_bindings {\nstruct Binding { const char* id; const char* surface; const char* kind; const char* owner; };\n")
set(ids)
set(surfaces)
foreach(entry IN LISTS entries)
  string(REGEX REPLACE ".*\\(cpb:([0-9][0-9][0-9][0-9]).*" "\\1" id "${entry}")
  string(REGEX REPLACE ".*\\(surface uk ([^)]+)\\).*" "\\1" surface "${entry}")
  string(REGEX REPLACE ".*\\(kind ([^)]+)\\).*" "\\1" kind "${entry}")
  string(REGEX REPLACE ".*\\(owner ([^)]+)\\).*" "\\1" owner "${entry}")
  list(FIND ids "${id}" repeated_id)
  list(FIND surfaces "${surface}" repeated_surface)
  if(NOT repeated_id EQUAL -1 OR NOT repeated_surface EQUAL -1)
    message(FATAL_ERROR "host binding registry has duplicate ID or surface: ${entry}")
  endif()
  list(APPEND ids "${id}")
  list(APPEND surfaces "${surface}")
  file(APPEND "${OUTPUT}" "inline constexpr Binding CPB_${id}{\"cpb:${id}\", \"${surface}\", \"${kind}\", \"${owner}\"};\n")
endforeach()
file(APPEND "${OUTPUT}" "} // namespace host_bindings\n")
